### ISSUE TITLE
did as you said and it not working

### ISSUE THREAD

**Issue by v3n0m30** [d7omdev/ags#2]
if i reload the witget it not showing anything i mean the whole  witget  and the lockscreen ias still not blurry

**Comment by d7omdev** [comment]
What do you mean? Mind showing a screenshot?
Certainly you changed something that broke the configs

**Comment by v3n0m30** [comment]
> What do you mean? Mind showing a screenshot? Certainly you changed something that broke the configs

fixed it what about the lockscreen?? not being blury even after uncommenting what am supposed to uncomment how can i fix that ??

**Comment by d7omdev** [comment]
I still don't understand what you are talking about, I really suggest you take the time to understand how everything works

**Comment by v3n0m30** [comment]
![image](https://github.com/user-attachments/assets/700285f3-05ab-4518-90bc-b080a38fcd7b)

**Comment by v3n0m30** [comment]
![image](https://github.com/user-attachments/assets/261689d9-6235-4857-81a3-d789b83aa396)

**Comment by v3n0m30** [comment]
![image](https://github.com/user-attachments/assets/b74d04c7-2688-4a72-a2cc-59b8ba53f1f6)

Is your Lock Screen blurry like this ?? This is not your age  this impulse what am saying is that in your config if I change my wallpaper and then lock my screen it won't work like get blurry like this and I don't know why even if I uncomment what am suppose to uncomment ![image](https://github.com/user-attachments/assets/c067bf4f-fc8d-498c-bffb-ce1ce928b645)

**Comment by v3n0m30** [comment]
try checking yours and see if it works

**Comment by v3n0m30** [comment]
![image](https://github.com/user-attachments/assets/7781027f-7be2-4491-96fa-31566486e593)

This is a clearer one

**Comment by v3n0m30** [comment]
![image](https://github.com/user-attachments/assets/6d8a3b8f-f879-40a5-b5c5-831a4962c302)

my hyprlock config

**Comment by v3n0m30** [comment]
![image](https://github.com/user-attachments/assets/34f1e4bf-5e6f-488e-acb9-bd05aed2230b)


i didnt touch anything other than the top monitors

though i just reinstall arch and the end-hyperland cuz when i did it before it works but when i re install it it just stopped working

**Comment by d7omdev** [comment]
What you're referring to is **Hyprlock**. It’s not configured by **AGS** and has nothing to do with it. As I said, you should learn how everything works first.  
although it's already working as expected I don't see where the issue is honestly... 

I’ll close this issue since it’s irrelevant to this repo, which is only for **AGS configs**, not **Hyprlock**.

**Comment by v3n0m30** [comment]
> What you're referring to is **Hyprlock**. It’s not configured by **AGS** and has nothing to do with it. As I said, you should learn how everything works first.  
> 
> although it's already working as expected I don't see where the issue is honestly... 
> 
> 
> 
> I’ll close this issue since it’s irrelevant to this repo, which is only for **AGS configs**, not **Hyprlock**.

So what about the widget not loading ??

**Comment by d7omdev** [comment]
run `ags` from the terminal and look for the logs you did something wrong, try removing your current configs and cloning this repo again if you can't figure it out

**Comment by taoki123** [comment]
bro have fixed it but am not getting popup notifications ?? do you know why or how i can fix it ??
